# Generated by Django 5.2.4 on 2025-07-29 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('LinearRegression', 'Linear Regression'), ('PolynomialRegression', 'Polynomial Regression'), ('DecisionTree', 'Decision Tree'), ('KNN', 'K-Nearest Neighbors'), ('RandomForest', 'Random Forest'), ('RidgeRegression', 'Ridge Regression')], max_length=50)),
                ('polynomial_degree', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('target_column', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='data/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('trained_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='trained_model.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/')),
                ('graph_json', models.TextField(blank=True, null=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='trained_model.trainedmodel')),
            ],
        ),
    ]
